### PR TITLE
Add support for altering from/to (Big)AutoField

### PR DESCRIPTION
**Pull request by marciobbj**
As @absci wrote at #55 I could start working on these changes. I did as explained, dropped the Primary Key, Foreign Keys, Unique Constraints, and Indexes, alter the table, then I managed to recreate the Primary Key constraint again.

### CODE REVIEW

**Comment by absci** [comment]
Thanks for your contribution! There're some unit tests that failed, could you run all unit tests and make sure there's no error related to this fix. 
Some details can be found here https://github.com/microsoft/mssql-django/blob/dev/CONTRIBUTING.md

You could also run individual tests related to altering Autofield. 
In `testapp/settings.py`, comment out `TEST_RUNNER = "testapp.runners.ExcludedTestSuiteRunner"` and run these test. 
```
'migrations.test_operations.OperationTests.test_autofield__bigautofield_foreignfield_growth',
'migrations.test_operations.OperationTests.test_smallfield_autofield_foreignfield_growth',
'migrations.test_operations.OperationTests.test_smallfield_bigautofield_foreignfield_growth',

'schema.tests.SchemaTests.test_alter_auto_field_to_char_field',
'schema.tests.SchemaTests.test_alter_auto_field_to_integer_field',
'schema.tests.SchemaTests.test_alter_int_pk_to_autofield_pk',
'schema.tests.SchemaTests.test_alter_int_pk_to_bigautofield_pk',
'schema.tests.SchemaTests.test_alter_auto_field_quoted_db_column',
'schema.tests.SchemaTests.test_alter_autofield_pk_to_bigautofield_pk_sequence_owner',
'schema.tests.SchemaTests.test_alter_autofield_pk_to_smallautofield_pk_sequence_owner',
'schema.tests.SchemaTests.test_alter_smallint_pk_to_smallautofield_pk',
```
One small thing is in `schema.py`, `IDENTITY (1, 1)` is already in `data_types_suffix`, hardcode that to `data_types` will likely cause some errors.

**Comment by marciobbj** [comment]
> 
> 
> Thanks for your contribution! There're some unit tests that failed, could you run all unit tests and make sure there's no error related to this fix.
> Some details can be found here https://github.com/microsoft/mssql-django/blob/dev/CONTRIBUTING.md
> 
> You could also run individual tests related to altering Autofield.
> In `testapp/settings.py`, comment out `TEST_RUNNER = "testapp.runners.ExcludedTestSuiteRunner"` and run these test.
> 
> ```
> 'migrations.test_operations.OperationTests.test_autofield__bigautofield_foreignfield_growth',
> 'migrations.test_operations.OperationTests.test_smallfield_autofield_foreignfield_growth',
> 'migrations.test_operations.OperationTests.test_smallfield_bigautofield_foreignfield_growth',
> 
> 'schema.tests.SchemaTests.test_alter_auto_field_to_char_field',
> 'schema.tests.SchemaTests.test_alter_auto_field_to_integer_field',
> 'schema.tests.SchemaTests.test_alter_int_pk_to_autofield_pk',
> 'schema.tests.SchemaTests.test_alter_int_pk_to_bigautofield_pk',
> 'schema.tests.SchemaTests.test_alter_auto_field_quoted_db_column',
> 'schema.tests.SchemaTests.test_alter_autofield_pk_to_bigautofield_pk_sequence_owner',
> 'schema.tests.SchemaTests.test_alter_autofield_pk_to_smallautofield_pk_sequence_owner',
> 'schema.tests.SchemaTests.test_alter_smallint_pk_to_smallautofield_pk',
> ```
> 
> One small thing is in `schema.py`, `IDENTITY (1, 1)` is already in `data_types_suffix`, hardcode that to `data_types` will likely cause some errors.

I just fixed the related tests... I had to add support for more migration cases, it was fun. And oh, you were right about the IDENTITY being hardcoded, I've fixed that too.

**Comment by absci** [comment]
Thanks for your contribution. But it seems the Django test suite was somehow broken by this commit. If you run two tests at the same time, for example below. 
```
python django/tests/runtests.py --settings=testapp.settings schema.tests.SchemaTests.test_alter_auto_field_to_char_field schema.tests.SchemaTests.test_alter_field_default_dropped
```
`_alter_field` also gets called, and the `id` field for the second test being overrode to `nvarchar`.

Another thing is there's one existing test in testapp failed. 
```
FAIL [0.010s]: test_partially_nullable (testapp.tests.test_constraints.TestPartiallyNullableUniqueTogether)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\a\_work\1\s\testapp\tests\test_constraints.py", line 50, in test_partially_nullable
    Post.objects.create(title="foo", author=author, alt_editor=editor)
AssertionError: IntegrityError not raised
```

**Comment by sg3-141-592** [comment]
I've done some testing on this and the issue I see is the `unique_together` index is getting dropped when migrating fields to `BigAutoField`.

If we look at migration `0012_alter_author_id.py` this is where I first see the issue. Looking at the database schema before and after we should just see the `author` models `id` field updated from `int` to `bigint`.

image

And the corresponding foreign key in the `post` table is successfully updated.

image

However if we look at the index updates, first on the `author` table some of the underlying index types have been changed

image

And in the `post` table we can see where we get a failing test for the `unique_together` clause because it's index has been dropped.

image

**Comment by marciobbj** [comment]
> I've done some testing on this and the issue I see is the `unique_together` index is getting dropped when migrating fields to `BigAutoField`.
> 
> If we look at migration `0012_alter_author_id.py` this is where I first see the issue. Looking at the database schema before and after we should just see the `author` models `id` field updated from `int` to `bigint`.
> 
> image
> 
> And the corresponding foreign key in the `post` table is successfully updated.
> 
> image
> 
> However if we look at the index updates, first on the `author` table some of the underlying index types have been changed
> 
> image
> 
> And in the `post` table we can see where we get a failing test for the `unique_together` clause because it's index has been dropped.
> 
> image

Thanks for pointing this out, it seems to be the problem... Maybe I missed something in the modifications I did in the `schema.py` file specifically in the `recreate_table_with_new_identity` method. Since I will not be able to work on this very soon I would be glad to test and give feedback on any commit you add on top of this PR.

**Comment by jmah8** [comment]
Closing this PR as PR #128 solves issue #55 and has been merged into dev.

**Pull request closed without merging**
