### PR TITLE
Backport fixes from django-mssql-backend

### PR DESCRIPTION
**Pull request by davidjb**
This PR features several PRs previously made on https://github.com/ESSolutions/django-mssql-backend: 

* Raise errors on trying to create conditions with unsupported constraints: https://github.com/ESSolutions/django-mssql-backend/pull/97 (open)
* Expand docs in README around `host_is_server`: https://github.com/ESSolutions/django-mssql-backend/pull/92 (merged)
* Backwards compatibility for `deferrable` kwarg: https://github.com/ESSolutions/django-mssql-backend/pull/86 (merged)

and fixes `manage.py` to be able to run tests; the hashbash line isn't first meaning it couldn't be executed as `./manage.py` directly.

### CODE REVIEW

**Review by absci — APPROVED** [review]

**Review by absci — APPROVED** [review]

**Review by absci — APPROVED** [review]

**Review by absci — APPROVED** [review]
Thanks for this contribution, this will help the user experience.

**Comment by davidjb** [comment]
Thanks @absci - much appreciated. Would it be possible to create a new PyPI release? Thank you!

**Comment by absci** [comment]
> Thanks @absci - much appreciated. Would it be possible to create a new PyPI release? Thank you!

No problem, we don't really have a schedule for the next release yet, but it should be soon.

**Comment by Trezorro** [comment]
Hi @absci I've trying to get MSSQL working with django 3.1, running into the issues metntioned here as well as  #25 . It seems like these should be fixed, but I don't see a new release on Pypi. Could you update us on the schedule? 
Meanwhile, is it save to install from src?

**Comment by absci** [comment]
> Hi @absci I've trying to get MSSQL working with django 3.1, running into the issues metntioned here as well as #25 . It seems like these should be fixed, but I don't see a new release on Pypi. Could you update us on the schedule?
> Meanwhile, is it safe to install from src?

It's generally safe to install from source, I don't have updates for the schedule yet.

**Comment by mbehn** [comment]
hi @absci I am trying to deploy with Django 3.2 and am having this same issue. Seeing if you might have an update on when Pypi will be updated.

**Comment by vwarchu** [comment]
Hi @mbehn , Pypi will be updated June 30, 2021 with version 1.0rc1. The GA release is scheduled to be released on Pypi on July 29, 2021. Cheers

**Pull request merged**
