### PR TITLE
Prepare for 1.3 release

### PR DESCRIPTION
**Pull request by mShan0**
Adds support for Django 4.2

Skips the following tests:
```
'aggregation.test_filter_argument.FilteredAggregateTests.test_filtered_aggregate_empty_condition',
'aggregation.test_filter_argument.FilteredAggregateTests.test_filtered_aggregate_ref_multiple_subquery_annotation',
'aggregation.test_filter_argument.FilteredAggregateTests.test_filtered_aggregate_ref_subquery_annotation',

"aggregation.tests.AggregateAnnotationPruningTests.test_referenced_group_by_annotation_kept"

'aggregation.tests.AggregateTestCase.test_group_by_nested_expression_with_params',

'expressions.tests.BasicExpressionsTests.test_aggregate_subquery_annotation',

'queries.test_qs_combinators.QuerySetSetOperationTests.test_union_order_with_null_first_last',
'queries.test_qs_combinators.QuerySetSetOperationTests.test_union_with_select_related_and_order',

'expressions_window.tests.WindowFunctionTests.test_limited_filter',

'schema.tests.SchemaTests.test_remove_ignored_unique_constraint_not_create_fk_index'
```

### CODE REVIEW

**Review by absci — CHANGES_REQUESTED** [review]
Should this be 1.3?
https://github.com/microsoft/mssql-django/pull/269/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L29

**Comment by mShan0** [comment]
> Should this be 1.3? https://github.com/microsoft/mssql-django/pull/269/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L29

Good point. Fixed

**Review by absci — APPROVED** [review]

**Comment by sparrowt** [comment]
These mega squash merges make the git history less useful 😢 e.g. the git blame for all the changes in this PR simply says "Prepare for 1.3 release" which is much less helpful than having the original commit message & PR.

Would it be possible to avoid this in future please? This has happened before albeit at the dev->master point (https://github.com/microsoft/mssql-django/issues/129).

**Comment by mShan0** [comment]
@sparrowt That was a mistake on our end. Thanks for letting us know, will be fixed for next release

**Pull request merged**
