### PR TITLE
Add capability to convert to and from AutoField and BigAutoField

### PR DESCRIPTION
**Pull request by sg3-141-592**
Fix for issue #55 building on top of the existing pull request #128 . When debugging #128 I noticed that the failing `TestPartiallyNullableUniqueTogether` test for this change was not related to the Pull Request, but was an issue with the existing alter type code that would occur for any `AutoField` / `BigAutoField` cast.

The issue that was occurring was that indexes and constraints were being lost as part of the conversion process.

This Pull Request is using a modified approach to #128 which tries to rebuild the target table with the requests changes. This approach to `AutoField` / `BigAutoField` casting is
* Removing all indexes and constraints from affected tables
* Doing the `int -> bigint` and `bigint -> int` casts on the primary keys
* Recreating all of the indexes and constraints back onto the affected tables

I have added 2 new migrations to `testapp` to ensure we test this functionality
- `0020_autofield_to_bigautofield.py` `AutoField` to `BigAutoField` for `Author` model
- `0021_multiple_autofield_to_bigauto.py` multiple `AutoField` to `BigAutoField` migrations and vice-versa, including migrations on tables with more complex relationships (like `unique_together`)

I've attached before and after details of the database schema to show the migration changes.
* [sp_help_0019.txt](https://github.com/microsoft/mssql-django/files/8619512/sp_help_0019.txt)
* [sp_help_0020.txt](https://github.com/microsoft/mssql-django/files/8619513/sp_help_0020.txt)
* [sp_help_0021.txt](https://github.com/microsoft/mssql-django/files/8619516/sp_help_0021.txt)

Tests are passing the mssql django test suite but it seems like we still have some failing CI checks in the main Django test suite but I'm not able to see CI results. Would one of the project maintainers be able to give me access or share what the current issue is? Running the complete Django regression tests is taking over an hour for a single Python Django combination.

### CODE REVIEW

**Comment by jmah8** [comment]
Thanks for contributing. The failing tests and their output are:
```
======================================================================
ERROR [2.597s]: test_rename_field_reloads_state_on_fk_target_changes (migrations.test_operations.OperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\a\_work\1\s\.tox\py310-django40\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\a\_work\1\s\.tox\py310-django40\lib\site-packages\mssql\base.py", line 598, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There are no primary or candidate keys in the referenced table 'alter_rename_field_reloads_state_on_fk_target_changes_pony' that match the referencing column list in the foreign key 'alter_rename_field_reloads_state_on_fk_target_changes_ponyrider_pony_id_e49519f3_fk'. (1776) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Could not create constraint or index. See previous errors. (1750)")

======================================================================
ERROR [2.200s]: test_alter_field_reloads_state_on_fk_target_changes (migrations.test_operations.OperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\a\_work\1\s\.tox\py310-django40\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\a\_work\1\s\.tox\py310-django40\lib\site-packages\mssql\base.py", line 598, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There are no primary or candidate keys in the referenced table 'alter_alter_field_reloads_state_on_fk_target_changes_rider' that match the referencing column list in the foreign key 'alter_alter_field_reloads_state_on_fk_target_changes_pony_rider_id_a4c8b5b8_fk'. (1776) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Could not create constraint or index. See previous errors. (1750)")

```

**Comment by JulianOrteil** [comment]
Subscribing to this and 128 because a company project I'm in charge of is waiting for this functionality. Thank you @sg3-141-592 for picking this back up :+1:

**Comment by sg3-141-592** [comment]
Thanks @JulianOrteil , this change looks like its working and passing CI currently. And I've tested it with the django-tables2 library I was having an issue with. So this is in a good state for a repo maintainer to start reviewing.

**Comment by jmah8** [comment]
@sg3-141-592 There are some excluded Django unit tests that test converting to and from autofields that are failing when I tested it locally. Could you remove these tests from the EXCLUDED_TESTS list in `settings.py` and fix the failing tests?
```
'migrations.test_operations.OperationTests.test_autofield__bigautofield_foreignfield_growth',
'migrations.test_operations.OperationTests.test_smallfield_autofield_foreignfield_growth',
'migrations.test_operations.OperationTests.test_smallfield_bigautofield_foreignfield_growth',
'migrations.test_operations.OperationTests.test_autofield_foreignfield_growth',

'schema.tests.SchemaTests.test_alter_auto_field_to_char_field',
'schema.tests.SchemaTests.test_alter_auto_field_to_integer_field',
'schema.tests.SchemaTests.test_alter_int_pk_to_bigautofield_pk',
'schema.tests.SchemaTests.test_alter_auto_field_quoted_db_column',
'schema.tests.SchemaTests.test_alter_autofield_pk_to_bigautofield_pk_sequence_owner',
'schema.tests.SchemaTests.test_alter_autofield_pk_to_smallautofield_pk_sequence_owner',
'schema.tests.SchemaTests.test_alter_smallint_pk_to_smallautofield_pk',
'schema.tests.SchemaTests.test_char_field_pk_to_auto_field',
```

The failing tests are:
```
======================================================================
ERROR [2.790s]: test_alter_auto_field_to_char_field (schema.tests.SchemaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mssql-django/.tox/py38-django40/lib/python3.8/site-packages/django/db/backends/utils.py", li
ne 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mssql-django/.tox/py38-django40/lib/python3.8/site-packages/mssql/base.py", line 598, in exe
cute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Identity column 'i
d' must be of data type int, bigint, smallint, tinyint, or decimal or numeric with a scale of 0, unencrypted, and co
nstrained to be nonnullable. (2749) (SQLExecDirectW)")

======================================================================
ERROR [2.147s]: test_alter_int_pk_to_autofield_pk (schema.tests.SchemaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mssql-django/.tox/py38-django40/lib/python3.8/site-packages/django/db/backends/utils.py", li
ne 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mssql-django/.tox/py38-django40/lib/python3.8/site-packages/mssql/base.py", line 598, in exe
cute
    return self.cursor.execute(sql, params)
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the va
lue NULL into column 'i', table 'test_default.dbo.INTEGERPK'; column does not allow nulls. INSERT fails. (515) (SQLE
xecDirectW)")

======================================================================
ERROR [1.671s]: test_alter_int_pk_to_bigautofield_pk (schema.tests.SchemaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mssql-django/.tox/py38-django40/lib/python3.8/site-packages/django/db/backends/utils.py", li
ne 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mssql-django/.tox/py38-django40/lib/python3.8/site-packages/mssql/base.py", line 598, in exe
cute
    return self.cursor.execute(sql, params)
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the va
lue NULL into column 'i', table 'test_default.dbo.INTEGERPK'; column does not allow nulls. INSERT fails. (515) (SQLE
xecDirectW)")

======================================================================
FAIL [2.199s]: test_alter_auto_field_to_integer_field (schema.tests.SchemaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mssql-django/django/tests/schema/tests.py", line 815, in test_alter_auto_field_to_integer_fi
eld
    Author.objects.create()
AssertionError: DatabaseError not raised
```

**Comment by jmah8** [comment]
@sg3-141-592 great questions.

For `test_alter_auto_field_to_char_field` I would agree it is an unusual data change and I think your suggestion of raising an exception telling the user this is unsupported works to not further increase the complexity. Since we are planning on not implementing that functionality we should put `test_alter_auto_field_to_char_field` back into the EXCLUDED_TESTS list in `settings.py`.

For `test_alter_auto_field_to_integer_field` a table with a non-autoincrementing primary key can be created using:
```
CREATE TABLE Test (
	id int PRIMARY KEY,
	a int,
)
```
From my testing the primary key must be provided in the insert statement like you said and does not require you to start from 1 or even add ids sequentially (i.e. can add id=10 then add id=2) but has the usual constraints of a primary keys (i.e. not null).

**Comment by JulianOrteil** [comment]
@sg3-141-592 Bump!

**Comment by sg3-141-592** [comment]
Hey @jmah8 , I think we've got this into to a good state.

Following on from your last comments, the scope of this pull request is to just provide support for `(Big)AutoField` conversions and modifications. This fixes the issue we see where Django libraries that have migrations for `Django >= 3.2` where the `DEFAULT_AUTO_FIELD` changed from `AutoField` to `BigAutoField` ([Django 3.2 - Release Notes](https://docs.djangoproject.com/en/4.0/releases/3.2/)).

I'm not providing any support for conversions outside of this, e.g. `Int to AutoField` or `AutoField to Varchar`. This is because of the added complexity of working around MS-SQL's limitations on altering identity fields. Someone could pick up trying to support this as a future change.

If a user tries to do a conversion outside of the supported `(Big)AutoField` conversions then they'll get the following exception
`NotImplementedError: the backend doesn't support altering from AutoField to IntegerField.`

So from the tests you've listed I've re-enabled the following
```
+ 'migrations.test_operations.OperationTests.test_autofield__bigautofield_foreignfield_growth',
+ 'migrations.test_operations.OperationTests.test_smallfield_autofield_foreignfield_growth',
+ 'migrations.test_operations.OperationTests.test_smallfield_bigautofield_foreignfield_growth',
+ 'migrations.test_operations.OperationTests.test_autofield_foreignfield_growth',

# Tests which modify to/from (Big)AutoField and properties of (Big)AutoField

+ 'schema.tests.SchemaTests.test_alter_auto_field_quoted_db_column',
+ 'schema.tests.SchemaTests.test_alter_autofield_pk_to_bigautofield_pk_sequence_owner',
+ 'schema.tests.SchemaTests.test_alter_autofield_pk_to_smallautofield_pk_sequence_owner',
```

And these conversion tests will stay disabled

```
'schema.tests.SchemaTests.test_alter_auto_field_to_char_field',
'schema.tests.SchemaTests.test_alter_auto_field_to_integer_field',
'schema.tests.SchemaTests.test_alter_int_pk_to_bigautofield_pk',
'schema.tests.SchemaTests.test_alter_smallint_pk_to_smallautofield_pk',
'schema.tests.SchemaTests.test_char_field_pk_to_auto_field',
```

Let me know if you think there's any further work needed.

**Comment by jmah8** [comment]
@sg3-141-592 thanks for all the hard work. Everything you said makes sense to me. I would agree that this PR is in a good state. We will start to review this PR shortly.

**Review by jmah8 — APPROVED** [review]

**Comment by koedal** [comment]
I installed the development branch today and tried to run the migrations in https://github.com/jazzband/django-push-notifications and it failed with `NotImplementedError: the backend doesn't support altering from/to AutoField.` Any ideas?

**Comment by sg3-141-592** [comment]
Hey @koedal, I just had a go and I was able to run those migrations on Django 4.0 and 3.2.

image

Do you mind running `pip freeze | grep -i "Django"` to see what versions of libraries you have? And to double check your Python environment is using the copy of the library from Git.

image

Also if there's any more specifics on where the migration failed that'd might help track the issue down to a particular migration file that'd be great.

**Comment by koedal** [comment]
Thank you so much for the quick reply @sg3-141-592 

The error comes from a 10th migration not listed in your migrations which was created when I ran `makemigrations` on my after adding the Django-push-notifications project.

```
 /home/theadmin/ltc-webapi/.venv/lib/python3.10/site-packages/push_notifications/migrations/0010_alter_apnsdevice_id_alter_gcmdevice_id_and_more.py
    - Alter field id on apnsdevice
    - Alter field id on gcmdevice
    - Alter field id on webpushdevice
    - Alter field id on wnsdevice
```

When I run the pip freeze I get

```
Django==4.0.4
django-extensions==3.1.5
django-push-notifications==3.0.0
djangorestframework==3.13.1
mssql-django==1.1.3
```

Maybe I didn't install the dev branch correctly? I did it with the following command.

```
pip install git+https://github.com/microsoft/mssql-django.git@dev
```

**Comment by koedal** [comment]
Turns out I had to uninstall mysql-django first and then install it again from the dev branch for it actually to take affect.

Now it work! Thanks again.

From pip freeze:

```
Django==4.0.4
django-extensions==3.1.5
django-push-notifications==3.0.0
djangorestframework==3.13.1
mssql-django @ git+https://github.com/microsoft/mssql-django.git@781e9bf9241e1c21a3593c1dbc644485eb681cd8
```

**Pull request merged**
